In [36]:
from src.config import load_env_variable
import requests
import pandas as pd
import json
from datetime import datetime
from pathlib import Path

In [7]:
# load fmp api key
api_key = load_env_variable("FMP_API_KEY")

# set ticker
symbol = "AAPL"

In [22]:
# api endpoint url
endpoint_url = "https://financialmodelingprep.com/stable/income-statement"

# api params
params = {
    "symbol": symbol,
    "apikey": api_key,
}

# api call
response = requests.get(url=endpoint_url, params=params, timeout=30)

# check status code
response.status_code # 200

200

In [9]:
# mask api key
safe_url = response.url.replace(api_key, "REDACTED")

print(safe_url)
print(response.status_code)
print(response.text[:1000])

https://financialmodelingprep.com/stable/income-statement?symbol=AAPL&apikey=REDACTED
200
[
  {
    "date": "2025-09-27",
    "symbol": "AAPL",
    "reportedCurrency": "USD",
    "cik": "0000320193",
    "filingDate": "2025-10-31",
    "acceptedDate": "2025-10-31 06:01:26",
    "fiscalYear": "2025",
    "period": "FY",
    "revenue": 416161000000,
    "costOfRevenue": 220960000000,
    "grossProfit": 195201000000,
    "researchAndDevelopmentExpenses": 34550000000,
    "generalAndAdministrativeExpenses": 27601000000,
    "sellingAndMarketingExpenses": 0,
    "sellingGeneralAndAdministrativeExpenses": 27601000000,
    "otherExpenses": 0,
    "operatingExpenses": 62151000000,
    "costAndExpenses": 283111000000,
    "netInterestIncome": 0,
    "interestIncome": 0,
    "interestExpense": 0,
    "depreciationAndAmortization": 11698000000,
    "ebitda": 144427000000,
    "ebit": 132729000000,
    "nonOperatingIncomeExcludingInterest": 321000000,
    "operatingIncome": 133050000000,
    "totalOtherIncomeExpensesNet": -321000000,
    "incomeBeforeTax": 132729000000,
    "incomeTaxE

In [10]:
# convert response to python json object
data = response.json()

# check type
print(type(data))

<class 'list'>

In [ ]:
# check number of records
len(data)

if len(data) == 1:
    raise ValueError("Insufficient data to calculate revenue growth CAGR")

5

In [ ]:
# check df shape
data[0]

{'date': '2025-09-27',
 'symbol': 'AAPL',
 'reportedCurrency': 'USD',
 'cik': '0000320193',
 'filingDate': '2025-10-31',
 'acceptedDate': '2025-10-31 06:01:26',
 'fiscalYear': '2025',
 'period': 'FY',
 'revenue': 416161000000,
 'costOfRevenue': 220960000000,
 'grossProfit': 195201000000,
 'researchAndDevelopmentExpenses': 34550000000,
 'generalAndAdministrativeExpenses': 27601000000,
 'sellingAndMarketingExpenses': 0,
 'sellingGeneralAndAdministrativeExpenses': 27601000000,
 'otherExpenses': 0,
 'operatingExpenses': 62151000000,
 'costAndExpenses': 283111000000,
 'netInterestIncome': 0,
 'interestIncome': 0,
 'interestExpense': 0,
 'depreciationAndAmortization': 11698000000,
 'ebitda': 144427000000,
 'ebit': 132729000000,
 'nonOperatingIncomeExcludingInterest': 321000000,
 'operatingIncome': 133050000000,
 'totalOtherIncomeExpensesNet': -321000000,
 'incomeBeforeTax': 132729000000,
 'incomeTaxExpense': 20719000000,
 'netIncomeFromContinuingOperations': 112010000000,
 'netIncomeFromDiscontinuedOperations': 0,
 'otherAdjustmentsToNetIncome': 0,
 'netIncome': 112010000000,
 'netIncomeDeductions': 0,
 'bottomLineNetIncome': 112010000000,
 'eps': 7.49,
 'epsDiluted': 7.46,
 'weightedAverageShsOut': 14948500000,
 'weightedAverageShsOutDil': 15004697000}

In [13]:
# convert list of records to df
df = pd.DataFrame(data)

# display df
df.head()

,date,symbol,reportedCurrency,cik,filingDate,acceptedDate,fiscalYear,period,revenue,costOfRevenue,...,netIncomeFromContinuingOperations,netIncomeFromDiscontinuedOperations,otherAdjustmentsToNetIncome,netIncome,netIncomeDeductions,bottomLineNetIncome,eps,epsDiluted,weightedAverageShsOut,weightedAverageShsOutDil
0,2025-09-27,AAPL,USD,0000320193,2025-10-31,2025-10-31 06:01:26,2025,FY,416161000000,220960000000,...,112010000000,0,0,112010000000,0,112010000000,7.49,7.46,14948500000,15004697000
1,2024-09-28,AAPL,USD,0000320193,2024-11-01,2024-11-01 06:01:36,2024,FY,391035000000,210352000000,...,93736000000,0,0,93736000000,0,93736000000,6.11,6.08,15343783000,15408095000
2,2023-09-30,AAPL,USD,0000320193,2023-11-03,2023-11-02 18:08:27,2023,FY,383285000000,214137000000,...,96995000000,0,0,96995000000,0,96995000000,6.16,6.13,15744231000,15812547000
3,2022-09-24,AAPL,USD,0000320193,2022-10-28,2022-10-27 18:01:14,2022,FY,394328000000,223546000000,...,99803000000,0,0,99803000000,0,99803000000,6.15,6.11,16215963000,16325819000
4,2021-09-25,AAPL,USD,0000320193,2021-10-29,2021-10-28 18:04:28,2021,FY,365817000000,212981000000,...,94680000000,0,0,94680000000,0,94680000000,5.67,5.61,16701272000,16864919000

In [14]:
# inspect columns
print(df.columns)

Index(['date', 'symbol', 'reportedCurrency', 'cik', 'filingDate',
       'acceptedDate', 'fiscalYear', 'period', 'revenue', 'costOfRevenue',
       'grossProfit', 'researchAndDevelopmentExpenses',
       'generalAndAdministrativeExpenses', 'sellingAndMarketingExpenses',
       'sellingGeneralAndAdministrativeExpenses', 'otherExpenses',
       'operatingExpenses', 'costAndExpenses', 'netInterestIncome',
       'interestIncome', 'interestExpense', 'depreciationAndAmortization',
       'ebitda', 'ebit', 'nonOperatingIncomeExcludingInterest',
       'operatingIncome', 'totalOtherIncomeExpensesNet', 'incomeBeforeTax',
       'incomeTaxExpense', 'netIncomeFromContinuingOperations',
       'netIncomeFromDiscontinuedOperations', 'otherAdjustmentsToNetIncome',
       'netIncome', 'netIncomeDeductions', 'bottomLineNetIncome', 'eps',
       'epsDiluted', 'weightedAverageShsOut', 'weightedAverageShsOutDil'],
      dtype='str')

In [ ]:
# helper function returning list of columns that contain certain strings
def search_df_columns(df:pd.DataFrame, name:str | list[str]) -> list[str]:

    if isinstance(name,str):
        name = [name]

    cleaned_name = [search_term.lower().strip() for search_term in name]

    return [col for col in df.columns if any(search_term in col.lower().strip() for search_term in cleaned_name)]

search_df_columns(df, ["sym", "date", "fiscal", "per", "rev"])

['date',
 'symbol',
 'filingDate',
 'acceptedDate',
 'fiscalYear',
 'period',
 'revenue',
 'costOfRevenue',
 'operatingExpenses',
 'nonOperatingIncomeExcludingInterest',
 'operatingIncome',
 'netIncomeFromContinuingOperations',
 'netIncomeFromDiscontinuedOperations']

In [25]:
# inspect cols needed to calculate rev growth CAGR
print(df[['date',
'symbol',
'fiscalYear',
'period',
'revenue']])

         date symbol fiscalYear period       revenue
0  2025-09-27   AAPL       2025     FY  416161000000
1  2024-09-28   AAPL       2024     FY  391035000000
2  2023-09-30   AAPL       2023     FY  383285000000
3  2022-09-24   AAPL       2022     FY  394328000000
4  2021-09-25   AAPL       2021     FY  365817000000

In [26]:
# keep only cols we need
revenue_df = df[["symbol", "date", "fiscalYear", "period", "revenue"]].copy()

# cofirm fiscalYear and revenue are numeric
revenue_df['fiscalYear'] = pd.to_numeric(revenue_df['fiscalYear'], errors="coerce")
revenue_df['revenue'] = pd.to_numeric(revenue_df['revenue'], errors="coerce")

# sort oldest to newest
revenue_df = revenue_df.sort_values('fiscalYear')

revenue_df

  symbol        date  fiscalYear period       revenue
4   AAPL  2021-09-25        2021     FY  365817000000
3   AAPL  2022-09-24        2022     FY  394328000000
2   AAPL  2023-09-30        2023     FY  383285000000
1   AAPL  2024-09-28        2024     FY  391035000000
0   AAPL  2025-09-27        2025     FY  416161000000

In [35]:
# calc rev growth CAGR
start_row = revenue_df.iloc[0]
end_row = revenue_df.iloc[-1]

start_year = start_row['fiscalYear']
end_year = end_row['fiscalYear']

start_revenue = start_row['revenue']
end_revenue = end_row['revenue']

number_of_years = end_year - start_year

rev_growth_cagr = (end_revenue / start_revenue) ** (1 / number_of_years) - 1
rev_growth_cagr_percent = round(rev_growth_cagr * 100, 2)

print(f"Start year: {start_year}")
print(f"End year: {end_year}")
print(f"Start revenue: {start_revenue}")
print(f"End revenue: {end_revenue}")
print(f"Number of years: {number_of_years}")
print(f"Revenue CAGR: {rev_growth_cagr:.4f}")
print(f"Revenue CAGR %: {rev_growth_cagr_percent:.2f}%")

Start year: 2021
End year: 2025
Start revenue: 365817000000
End revenue: 416161000000
Number of years: 4
Revenue CAGR: 0.0328
Revenue CAGR %: 3.28%